version: "1.0"

services:
  # The web container is an instance of exactly the same Docker image as your
  # Cloud application container.
  web:
    build: .
    command: npm start
    # Change the port if you'd like to expose your project locally on a
    # different port, for example if you already use port 8000 for
    # something else.
    ports:
      - "8000:80"
    volumes:
    - .:/usr/src/app/:rw
    - /usr/src/app/node_modules

 