name: CI/CD for React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and deploy to GitHub Pages
        run: |
          npm run build
          npx gh-pages -d build

      - name: Deploy to hosting service (adjust as needed)
        # You can add additional steps here to deploy to other hosting services like Netlify, Vercel, etc.
        # Example for Netlify: https://github.com/netlify/actions/blob/master/checkout/netlify/checkout.yml
